"""
AI Code Analyzer — multi-provider (Groq → Gemini → Ollama)

The analyzer reads every source file, finds syntax errors, and fixes them.
Provider priority (first with a valid API key wins):
  1. Groq    — primary. Uses native JSON mode so the output is ALWAYS
               valid JSON, which eliminates the parse-time syntax errors
               we previously hit with Gemini's prose-mixed responses.
  2. Gemini  — fallback.
  3. Ollama  — local last-resort fallback.

Override the provider with env var AI_PROVIDER=groq|gemini|ollama.

Supports three fix actions:
  replace       — overwrite an existing broken line
  insert_before — insert a new line before an anchor line
  insert_after  — insert a new line after an anchor line
"""

import os
import sys
import json
import subprocess
import time
from collections import defaultdict

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ANALYSIS_LOG = os.path.join(PROJECT_ROOT, "analysis_output.txt")

SKIP_DIRS = {
    "venv", "__pycache__", ".git", ".pytest_cache", "node_modules",
    # Build outputs — never analyze these. The AI was "fixing" minified
    # JS bundles in client/dist/, which is auto-generated on every build.
    "dist", "build", ".next", ".cache", "out", ".vite",
}
SKIP_FILES = {
    "analysis_output.txt",
    "validation_output.txt",
    "test_output.txt",
    "lint_output.txt",
    "trivy-report.json",
    # Lockfiles are machine-generated. The AI hallucinated "missing closing
    # braces" in package-lock.json and inserted stray }s, which broke
    # `npm ci`. Lockfiles must be regenerated by npm/yarn, never hand-edited
    # by the AI.
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Pipfile.lock",
    "poetry.lock",
}
ANALYZE_EXTS = {".py", ".html", ".htm", ".js", ".jsx", ".ts", ".tsx", ".css", ".json"}

# Skip any file whose name matches these patterns (minified bundles, source
# maps, etc. — also auto-generated and never worth fixing).
SKIP_FILE_PATTERNS = ("min.js", "min.css", ".map", "bundle.js")

# ── Cross-batch run state ─────────────────────────────────────────
# When we send many batches, we don't want to re-enumerate every model on
# every batch. Once a Groq model works, stick with it. Once a provider is
# known dead (auth, rate-limit, Ollama not installed), skip it for the rest
# of the run instead of re-discovering the failure on every batch.
_RUN_STATE = {
    "groq_model": None,       # model name that worked — try this first next time
    "gemini_model": None,
    "groq_dead": False,       # hard-disabled for this run (auth error, etc.)
    "gemini_dead": False,
    "ollama_dead": False,
}
# Hard wall-clock budget for the whole AI-analysis step. If we cross this
# many seconds, bail out with whatever we have and let the pipeline move on.
# Override with env AI_ANALYSIS_BUDGET_SECS.
AI_ANALYSIS_BUDGET_SECS = int(os.environ.get("AI_ANALYSIS_BUDGET_SECS", "600"))  # 10 min
_RUN_START_TIME = None  # set in main() when analysis begins

# Max chars per SINGLE file chunk — must stay well under Groq's per-request
# token budget once all other overhead (system prompt, schema, etc.) is added.
# With the old 80 000 value, a full repo scan blew past Groq's max-request size
# and we'd get "400 — Please reduce the length of the messages or completion."
MAX_CHUNK_CHARS = 20000
# If a file exceeds this, split it into overlapping chunks so no line is missed
CHUNK_OVERLAP = 2000  # overlap between chunks to catch errors at split boundaries
# Max total chars per BATCH sent to the AI (multiple small files packed together).
# Keeping the batch below ~25 KB means the full prompt (files + system + schema)
# stays well under the typical 8 K-output-token budget Groq allows per request.
MAX_BATCH_CHARS = 25000


# ── Collect source files (with chunking for large files) ─────────


def split_into_chunks(content, rel_path):
    """
    Split a large file into overlapping line-based chunks so no line is skipped.
    Each chunk keeps a small overlap with the previous to catch errors at boundaries.
    Returns list of (chunk_label, chunk_content) tuples.
    """
    lines = content.splitlines(keepends=True)
    chunks = []
    start_line = 0
    chunk_idx = 1

    while start_line < len(lines):
        chunk_lines = []
        char_count = 0
        end_line = start_line

        while end_line < len(lines) and char_count < MAX_CHUNK_CHARS:
            chunk_lines.append(lines[end_line])
            char_count += len(lines[end_line])
            end_line += 1

        label = f"{rel_path} [chunk {chunk_idx}, lines {start_line+1}–{end_line}]"
        chunks.append((label, rel_path, start_line + 1, "".join(chunk_lines)))

        # Move forward, but keep CHUNK_OVERLAP chars of overlap
        overlap_chars = 0
        overlap_line = end_line
        while overlap_line > start_line and overlap_chars < CHUNK_OVERLAP:
            overlap_line -= 1
            overlap_chars += len(lines[overlap_line])

        start_line = overlap_line
        # If we didn't advance, force forward to avoid infinite loop
        if start_line <= (chunk_idx - 1) * (end_line - start_line):
            start_line = end_line
        chunk_idx += 1

    return chunks


def collect_files():
    """
    Collect all source files. Large files are split into chunks so the AI
    sees every line — no more silent truncation in the middle of a file.
    Returns dict: label → {"rel_path": ..., "line_start": ..., "content": ...}
    """
    file_map = {}

    for dirpath, dirnames, filenames in os.walk(PROJECT_ROOT):
        dirnames[:] = [
            d for d in dirnames if d not in SKIP_DIRS and not d.startswith(".")
        ]
        for filename in filenames:
            if filename in SKIP_FILES:
                continue
            # Skip minified bundles, source maps, etc.
            if any(filename.endswith(pat) for pat in SKIP_FILE_PATTERNS):
                continue
            ext = os.path.splitext(filename)[1].lower()
            if ext not in ANALYZE_EXTS:
                continue
            full_path = os.path.join(dirpath, filename)
            rel_path = os.path.relpath(full_path, PROJECT_ROOT)
            try:
                with open(full_path, "r", encoding="utf-8", errors="replace") as f:
                    content = f.read()

                if len(content) <= MAX_CHUNK_CHARS:
                    # Small file — send as-is
                    file_map[rel_path] = {
                        "rel_path": rel_path,
                        "line_start": 1,
                        "content": content,
                    }
                else:
                    # Large file — split into chunks (NO truncation)
                    chunks = split_into_chunks(content, rel_path)
                    print(
                        f"  ⚡ Large file split into {len(chunks)} chunk(s): {rel_path}"
                    )
                    for label, rp, line_start, chunk_content in chunks:
                        file_map[label] = {
                            "rel_path": rp,
                            "line_start": line_start,
                            "content": chunk_content,
                        }

            except Exception as e:
                print(f"  Warning: could not read {rel_path} — {e}")

    return file_map


# ── Build Gemini prompt ───────────────────────────────────────────


def build_prompt(files_dict):
    file_sections = ""
    for label, meta in files_dict.items():
        content = meta["content"]
        line_start = meta["line_start"]
        # Number each line with its TRUE line number in the original file
        numbered = "\n".join(
            f"{line_start + i:4d} | {line}"
            for i, line in enumerate(content.splitlines())
        )
        file_sections += f"\n{'='*60}\nFILE: {label}\n{'='*60}\n{numbered}\n"

    prompt = f"""You are a CI/CD self-healing agent. Analyze every file below and find
ALL syntax errors that would cause the code to fail, crash, or render incorrectly.

Project files:
{file_sections}

════════════════════════════════════════
WHAT TO FIND — errors in ANY language:

Python  : missing colon (def/if/for/class), wrong indentation, unclosed bracket,
          undefined name used as function, invalid syntax
HTML/JSX: missing required tags (<html>, <head>, <body>, <style>, <script>),
          tag written as <lang="en"> instead of <html lang="en">,
          unclosed tags, TYPO'D TAG NAMES — any tag that isn't a valid HTML5
          element or React component is almost certainly a typo.
          Examples you MUST flag and fix (this list is NOT exhaustive — flag
          ANY tag whose name isn't a valid HTML5 element):
            <riv>   → <div>        </riv>   → </div>
            <dvi>   → <div>        </dvi>   → </div>
            <dv>    → <div>        </dv>    → </div>
            <diiv>  → <div>        </diiv>  → </div>
            <ivd>   → <div>        </ivd>   → </div>
            <spam>  → <span>       </spam>  → </span>
            <span>...</spam> → mismatched, fix the closing to </span>
            <butto> → <button>     <buton>  → <button>
            <h1>...</H1> → </h1>   (case mismatch — closing tag must match)
          The rule: if a closing tag's name doesn't EXACTLY match the
          nearest opening tag's name, ONE of them is a typo — fix the
          typo'd one to match the valid HTML5 element.
          If both the opening and closing tag are typo'd the same way
          (e.g. <riv>...</riv>), produce TWO replace issues — one per line.
CSS     : unclosed braces {{ }}, missing semicolons on property values
JavaScript / JSX : missing semicolons, unclosed brackets/braces, undefined
          variables, invalid JSX element names (same tag-typo rule as HTML)
JSON    : trailing commas, unquoted keys, mismatched brackets

WHAT NOT TO REPORT:
  - Code style, naming, or formatting preferences
  - Logic improvements or refactoring
  - Warnings that don't break execution

════════════════════════════════════════
THREE FIX ACTIONS — use the right one:

1. "replace"       — a line EXISTS but is broken; overwrite it with the fix
   Example: <lang="en">  →  replace with  <html lang="en">

2. "insert_before" — a required line is COMPLETELY MISSING; insert the new line
                     BEFORE the anchor_line you specify
   Example: <style> tag is missing before `:root {{`

3. "insert_after"  — a required line is COMPLETELY MISSING; insert the new line
                     AFTER the anchor_line you specify
   Example: <head> tag is missing after `<html lang="en">`

RULES FOR ALL ACTIONS:
  • anchor_line / original_line must be copied EXACTLY from the file (character for character)
  • fixed_line MUST BE A SINGLE LINE — absolutely no \\n, no newlines, no line breaks of any kind
  • If you need to insert multiple lines, create one issue object per line
  • fixed_line must not be empty
  • For "replace": original_line and fixed_line must differ
  • DO NOT invent file paths — only report issues in files shown above between the === markers

════════════════════════════════════════
ABSOLUTE RULES — NEVER BREAK THESE:

  ✅ DO fix typo'd tag names by replacing them with the intended VALID tag.
     If you see <riv>, <dv>, <iv>, <dt>, <spam>, <butto> or any other tag
     name that is NOT a standard HTML5 element or a valid React component,
     treat it as a typo and REPLACE it with the closest valid tag
     (<riv>/<dv>/<iv> → <div>, <spam> → <span>, <butto> → <button>, etc.).

  ❌ NEVER INVENT a tag name that is not in the HTML5 standard. The
     fixed_line must ONLY ever contain standard HTML5 tags (<div>, <span>,
     <p>, <section>, <a>, <button>, <form>, <input>, <img>, <ul>, <li>, …).
     If you can't figure out what the user meant, leave the line alone.

  ❌ NEVER rename a tag that IS already a valid HTML5 element. <div> stays
     <div>. <span> stays <span>. Only touch tags that are clearly typos.

  ❌ NEVER fix what is not broken. If a line has no error, do not touch it.

  ❌ NEVER produce a fixed_line that itself contains a made-up tag such as
     <jt>, <ht>, <bt>, <riv>, <spam>, or anything not in HTML5.

════════════════════════════════════════
Return ONLY raw JSON — no markdown, no code fences.

If no errors found:
{{"status": "clean", "message": "No syntax errors found", "issues": []}}

If errors found:
{{
  "status": "issues_found",
  "summary": "one sentence describing all errors found",
  "issues": [
    {{
      "file_path": "relative/path/to/file",
      "language": "python|html|css|javascript|json",
      "line_number": 42,
      "action": "replace|insert_before|insert_after",
      "original_line": "exact line from file (anchor for insert, broken line for replace)",
      "fixed_line": "the corrected or new single line",
      "description": "one sentence: what syntax error this fixes",
      "severity": "error"
    }}
  ]
}}"""
    return prompt


# ── Call Groq (primary) ───────────────────────────────────────────


def call_groq_analyze(prompt):
    """
    Primary provider. Uses Groq's native JSON mode so the API response is
    guaranteed to be a syntactically valid JSON object — this prevents the
    "Expecting value: line X column Y" errors we'd hit when a model returns
    prose mixed with JSON.

    Requires:
      pip install groq
      GROQ_API_KEY env var

    Returns the raw text response (a JSON string) on success, or None on
    complete failure so the caller can fall back to another provider.
    """
    # Short-circuit: if we already discovered Groq is unusable this run,
    # don't waste another batch on auth / rate-limit errors.
    if _RUN_STATE["groq_dead"]:
        print("  Groq already marked unavailable for this run — skipping")
        return None

    try:
        from groq import Groq
    except ImportError:
        print("  groq SDK not installed (pip install groq) — skipping Groq")
        _RUN_STATE["groq_dead"] = True
        return None

    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        print("  GROQ_API_KEY not set — skipping Groq")
        _RUN_STATE["groq_dead"] = True
        return None

    client = Groq(api_key=api_key)

    # Ordered by quality for code-analysis tasks. All currently live on Groq
    # (as of late 2025) and support JSON mode.
    DEFAULT_MODELS = [
        "llama-3.3-70b-versatile",   # best general-purpose, strong at code (128K ctx)
        "llama-3.1-8b-instant",      # fast small model, last resort (128K ctx)
        "llama3-70b-8192",           # stable older-gen fallback (8K ctx)
        "llama3-8b-8192",            # tiny stable fallback (8K ctx)
        "gemma2-9b-it",              # extra fallback
    ]

    # If we already found a working model on a previous batch, try it first —
    # avoids re-discovering 404s for the decommissioned models on every batch.
    if _RUN_STATE["groq_model"]:
        models = [_RUN_STATE["groq_model"]] + [
            m for m in DEFAULT_MODELS if m != _RUN_STATE["groq_model"]
        ]
    else:
        models = DEFAULT_MODELS

    # JSON mode requires the word "JSON" somewhere in the prompt — our
    # build_prompt() already includes it, but we belt-and-braces it here.
    system_msg = (
        "You are a code analyzer. Respond with ONE raw JSON object only. "
        "Do not wrap it in markdown or include any prose. Your entire response "
        "must be valid JSON."
    )

    for model_name in models:
        for attempt in range(3):
            try:
                print(f"  Trying Groq model {model_name} (attempt {attempt + 1})...")
                response = client.chat.completions.create(
                    model=model_name,
                    messages=[
                        {"role": "system", "content": system_msg},
                        {"role": "user", "content": prompt},
                    ],
                    temperature=0.1,  # low temp = deterministic, fewer syntax errors
                    max_tokens=8192,
                    response_format={"type": "json_object"},  # <-- guarantees valid JSON
                )
                text = (response.choices[0].message.content or "").strip()
                if text:
                    print(f"  ✓ Got JSON response from Groq ({model_name})")
                    _RUN_STATE["groq_model"] = model_name  # cache for next batch
                    return text
                print(f"  {model_name} returned empty body — trying next model...")
                break

            except Exception as e:
                err = str(e)
                # Rate limit — try next model (Groq's quotas are per-model)
                if "429" in err or "rate_limit" in err.lower():
                    print(f"  {model_name} rate-limited (429) — trying next model...")
                    break
                # Decommissioned / not found
                if "404" in err or "model_not_found" in err.lower() or "decommissioned" in err.lower():
                    print(f"  {model_name} not available (404) — skipping...")
                    break
                # Server error — backoff and retry same model
                if "503" in err or "500" in err or "timeout" in err.lower():
                    wait = 5 * (attempt + 1)
                    print(f"  {model_name} server error: {e} — retrying in {wait}s")
                    if attempt < 2:
                        time.sleep(wait)
                        continue
                    break
                # Auth / other hard error — stop trying Groq entirely for this run
                if "401" in err or "invalid_api_key" in err.lower() or "auth" in err.lower():
                    print(f"  Groq auth error: {e} — is GROQ_API_KEY correct?")
                    _RUN_STATE["groq_dead"] = True
                    return None
                print(f"  {model_name} unexpected error: {e} — skipping")
                break

    # If we got here, every Groq model failed for THIS batch. On the free
    # tier this almost always means the per-minute token quota is blown. No
    # point re-enumerating all 5 models on the next batch — mark Groq dead
    # for the rest of this run. The outer loop will fall straight to Gemini.
    print("  All Groq models unavailable — disabling Groq for the rest of this run.")
    _RUN_STATE["groq_dead"] = True
    return None


# ── Call Gemini (fallback) ────────────────────────────────────────


def call_gemini_analyze(prompt):
    # Short-circuit if Gemini is already known dead this run (rate-limit, etc.)
    if _RUN_STATE["gemini_dead"]:
        print("  Gemini already marked unavailable for this run — skipping")
        return None

    if not os.environ.get("GEMINI_API_KEY"):
        print("  GEMINI_API_KEY not set — skipping Gemini")
        _RUN_STATE["gemini_dead"] = True
        return None

    try:
        from google import genai
        from google.genai import errors as genai_errors
    except ImportError:
        print("  google-genai SDK not installed — skipping Gemini")
        _RUN_STATE["gemini_dead"] = True
        return None

    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

    DEFAULT_MODELS = [
        "gemini-2.5-flash",
        "gemini-2.5-pro",
        "gemini-2.0-flash",
        "gemini-2.0-flash-lite",
        "gemini-1.5-flash",
        "gemini-1.5-pro",
    ]
    # Stick with whichever model worked on the previous batch.
    if _RUN_STATE["gemini_model"]:
        models = [_RUN_STATE["gemini_model"]] + [
            m for m in DEFAULT_MODELS if m != _RUN_STATE["gemini_model"]
        ]
    else:
        models = DEFAULT_MODELS

    rate_limited_count = 0

    for model_name in models:
        # Single attempt per model — retries multiplied across many batches
        # are what made Gemini's path take 10+ minutes per build.
        try:
            print(f"  Trying {model_name}...")
            response = client.models.generate_content(
                model=model_name, contents=prompt
            )
            print(f"  ✓ Got response from {model_name}")
            _RUN_STATE["gemini_model"] = model_name  # cache for next batch
            return response.text.strip()

        except genai_errors.ClientError as e:
            err = str(e)
            if "429" in err or "RESOURCE_EXHAUSTED" in err:
                print(f"  {model_name} rate-limited (429) — trying next model...")
                rate_limited_count += 1
                continue
            elif "404" in err or "NOT_FOUND" in err:
                print(f"  {model_name} not found (404) — skipping...")
                continue
            else:
                print(f"  {model_name} client error: {e} — skipping")
                continue

        except genai_errors.ServerError as e:
            # 503 — try next model immediately. No 20s backoff, no 2-min sleep.
            print(f"  {model_name} server error: {e} — trying next model...")
            continue

        except Exception as e:
            print(f"  {model_name} unexpected error: {e} — skipping")
            continue

    # If EVERY Gemini model is rate-limited, the free-tier quota is exhausted
    # for this minute. Mark Gemini dead for the rest of the run instead of
    # banging on the API again on the next batch (would just waste seconds).
    if rate_limited_count == len(models):
        print("  All Gemini models rate-limited — disabling Gemini for the rest of this run.")
        _RUN_STATE["gemini_dead"] = True

    # NOTE: do NOT internally fall through to Ollama here. The outer batched
    # loop handles provider fallback per batch, and the previous nested
    # fallthrough caused Ollama to be called twice and added 2-min sleeps.
    return None


# ── Ollama local fallback ─────────────────────────────────────────


def call_ollama_analyze(prompt):
    """
    Fallback: call a locally running Ollama model when all Gemini models fail.
    Ollama must be running: `ollama serve`
    Preferred models (install with `ollama pull <model>`):
      ollama pull codellama        (best for code analysis)
      ollama pull deepseek-coder   (great alternative)
      ollama pull llama3           (general purpose fallback)
    """
    # Short-circuit: if Ollama is already known dead/slow this run, skip it.
    # Without this, every batch would re-discover the same failure and add
    # minutes of timeouts to the build.
    if _RUN_STATE["ollama_dead"]:
        print("  Ollama already marked unavailable for this run — skipping")
        return None

    import urllib.request
    import urllib.error

    OLLAMA_URL = "http://localhost:11434/api/generate"

    # Try these models in order — use whichever is installed
    models = ["codellama", "deepseek-coder", "llama3", "mistral", "llama2"]

    # Force Ollama to return ONLY raw JSON — no narrative, no markdown
    json_instruction = (
        "CRITICAL INSTRUCTION: You must respond with ONLY raw JSON. "
        "Do NOT write any explanation, introduction, commentary, or markdown. "
        "Do NOT use code fences (``` or ```json). "
        "Your ENTIRE response must start with { and end with }. "
        "Any response that is not pure JSON will be rejected.\n\n"
    )
    ollama_prompt = json_instruction + prompt

    # Tighter timeouts — batches are now ≤25 KB so CPU-only Ollama should
    # answer in under 90 s. Keeping codellama's old 360 s × 2 attempts ×
    # 6 batches turned every Jenkins build into a 30+ min wait.
    TIMEOUTS = {
        "codellama":      120,
        "deepseek-coder": 120,
        "llama3":         120,
        "mistral":        90,
        "llama2":         120,
    }
    DEFAULT_TIMEOUT = 90

    for model_name in models:
        timeout = TIMEOUTS.get(model_name, DEFAULT_TIMEOUT)
        # Single attempt per model — earlier code did 2 retries for codellama
        # which doubled the worst-case wait per batch.
        max_attempts = 1

        for attempt in range(max_attempts):
            try:
                attempt_label = (
                    f" (attempt {attempt+1}/{max_attempts})" if max_attempts > 1 else ""
                )
                print(
                    f"  Trying Ollama model: {model_name}{attempt_label} (timeout={timeout}s)..."
                )
                payload = json.dumps(
                    {
                        "model": model_name,
                        "prompt": ollama_prompt,
                        "stream": False,
                        "format": "json",  # Ollama native JSON mode
                        "options": {
                            "temperature": 0.1,  # low temp = more deterministic JSON
                            "num_predict": 2048,  # capped: JSON response doesn't need 4096 tokens
                        },
                    }
                ).encode("utf-8")

                req = urllib.request.Request(
                    OLLAMA_URL,
                    data=payload,
                    headers={"Content-Type": "application/json"},
                    method="POST",
                )
                req.add_header("Connection", "keep-alive")

                with urllib.request.urlopen(req, timeout=timeout) as resp:
                    result = json.loads(resp.read().decode("utf-8"))
                    text = result.get("response", "").strip()
                    if text:
                        print(f"  ✓ Got response from Ollama ({model_name})")
                        return text
                    else:
                        print(
                            f"  {model_name} returned empty response — trying next..."
                        )
                break  # success or empty — don't retry

            except urllib.error.URLError as e:
                err_str = str(e)
                if "Connection refused" in err_str or "Connection reset" in err_str:
                    print("  Ollama is not running on this machine.")
                    print(
                        "  To enable: install Ollama (https://ollama.com) then run: ollama serve"
                    )
                    _RUN_STATE["ollama_dead"] = True  # don't retry on later batches
                    return None
                if "404" in err_str or "Not Found" in err_str:
                    print(
                        f"  Ollama {model_name}: model not installed — trying next..."
                    )
                    break  # model not installed, no point retrying
                print(f"  Ollama {model_name} error: {e} — trying next model...")
                break

            except TimeoutError as e:
                if attempt < max_attempts - 1:
                    print(
                        f"  Ollama {model_name} timed out after {timeout}s — retrying once..."
                    )
                else:
                    print(
                        f"  Ollama {model_name} timed out after {timeout}s — trying next model..."
                    )

            except Exception as e:
                err_str = str(e)
                if "timed out" in err_str.lower():
                    if attempt < max_attempts - 1:
                        print(f"  Ollama {model_name} timed out — retrying once...")
                    else:
                        print(f"  Ollama {model_name} timed out — trying next model...")
                else:
                    print(
                        f"  Ollama {model_name} unexpected error: {e} — trying next model..."
                    )
                    break  # non-timeout error, move on

    print("  No Ollama models responded. Install one with: ollama pull codellama")
    return None


# ── Validate a fix before applying ───────────────────────────────


def _sanitize_line(value):
    """
    Strip embedded newlines from a field the AI returned as multi-line.
    The AI is instructed to return single lines; if it disobeys, take the
    first non-empty line so we salvage the fix rather than discard it.
    """
    if "\n" in value:
        first = next((l for l in value.split("\n") if l.strip()), "")
        return first
    # Handle JSON-escaped literal \n sequences
    if "\\n" in value:
        first = next((l for l in value.split("\\n") if l.strip()), "")
        return first
    return value


def is_safe_fix(issue):
    action = issue.get("action", "replace")
    orig = issue.get("original_line", "")
    fixed = issue.get("fixed_line", "")
    file_path = issue.get("file_path", "")
    loc = f"{file_path} line {issue.get('line_number')}"

    # ── Path-based safety: reject fixes in files that should never be edited
    # by the AI even if they slipped past the file collector. ───────────
    BANNED_PATH_FRAGMENTS = (
        "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
        "Pipfile.lock", "poetry.lock",
        "/dist/", "/build/", "/node_modules/",
        ".min.js", ".min.css", ".map",
    )
    norm = file_path.replace("\\", "/")
    for frag in BANNED_PATH_FRAGMENTS:
        if frag in norm:
            print(f"  ⛔ Skipping fix in protected path ({frag}): {loc}")
            return False

    # ── Hallucination guard: AI loves to "fix" newer-than-its-training-data
    # API model names back to older ones. Reject any replace fix where the
    # before/after lines look like API/model identifier strings. ────────
    HALLUCINATION_TOKENS = (
        "llama-3", "llama3", "gemini-2", "gemini-1", "gemini-pro",
        "claude-3", "claude-2", "gpt-4", "gpt-3", "o1-", "o3-",
        "mixtral", "mistral", "deepseek", "gemma",
    )
    if action == "replace":
        orig_low = orig.lower()
        fixed_low = fixed.lower()
        if any(t in orig_low or t in fixed_low for t in HALLUCINATION_TOKENS):
            print(f"  ⛔ Skipping suspected model-name hallucination at {loc}")
            print(f"     before: {orig.strip()[:80]}")
            print(f"     after : {fixed.strip()[:80]}")
            return False

    # ── Insert-after `pass` is almost always wrong: the AI inserts a stub
    # body after a docstring of a function that already has a body. ─────
    if action in ("insert_before", "insert_after") and fixed.strip() == "pass":
        print(f"  ⛔ Skipping suspicious 'pass' insertion at {loc}")
        return False

    # ── Insert-after a lone closing brace `}` — the AI was inventing
    # missing braces in valid JSON files (broke package-lock.json). ─────
    if action in ("insert_before", "insert_after") and fixed.strip() in ("}", "]", "},"):
        print(f"  ⛔ Skipping bare-brace insertion at {loc} — too risky")
        return False

    # ── Import-path hallucination guard ─────────────────────────────
    # When the AI "fixes" an `import ... from 'A'` to import from a
    # different module 'B', it's almost always hallucinating. The classic
    # case: changing `import { protect } from '../middleware/authMiddleware.js'`
    # to `import { protect, login } from '../controllers/authController.js'`.
    # The file compiles but crashes at startup because the symbol doesn't
    # exist in the new module. We reject any replace that swaps the source
    # path of an import statement.
    if action == "replace":
        import re as _re_imp
        # Match: import ... from 'path' OR import ... from "path"
        imp_re = _re_imp.compile(r"""\bfrom\s+['"]([^'"]+)['"]""")
        before_match = imp_re.search(orig)
        after_match  = imp_re.search(fixed)
        if before_match and after_match:
            before_path = before_match.group(1)
            after_path  = after_match.group(1)
            if before_path != after_path:
                print(f"  ⛔ Skipping import-path swap at {loc}")
                print(f"     Refused to redirect import from {before_path!r} to {after_path!r}")
                print(f"     (this is a common AI hallucination — the symbol may not exist in the new module)")
                return False

    # anchor/original must not be empty
    if not orig.strip():
        print(f"  ⚠ Skipping — empty original_line/anchor for {loc}")
        return False

    # Sanitize: if AI returned multi-line values, keep only the first line
    if "\n" in orig or "\\n" in orig:
        orig = _sanitize_line(orig)
        issue["original_line"] = orig
        print(f"  ℹ  Trimmed multi-line original_line to first line for {loc}")

    if "\n" in fixed or "\\n" in fixed:
        fixed = _sanitize_line(fixed)
        issue["fixed_line"] = fixed
        print(f"  ℹ  Trimmed multi-line fixed_line to first line for {loc}")

    # After sanitization, both fields must still have content
    if not orig.strip():
        print(f"  ⚠ Skipping — original_line empty after sanitization for {loc}")
        return False
    if not fixed.strip():
        print(f"  ⚠ Skipping — fixed_line empty after sanitization for {loc}")
        return False

    # for replace: the two lines must actually differ
    if action == "replace" and orig == fixed:
        print(f"  ⚠ Skipping no-op replace (original == fixed) for {loc}")
        return False

    if action not in ("replace", "insert_before", "insert_after"):
        print(f"  ⚠ Unknown action '{action}' for {loc}")
        return False

    return True


# ── Apply a single fix ────────────────────────────────────────────


def apply_fix(issue):
    """Apply a fix and return the actual line number found, or False on failure."""
    file_path = issue["file_path"]
    action = issue.get("action", "replace")
    line_number = issue.get("line_number")
    original = issue.get("original_line", "")
    fixed = issue.get("fixed_line", "")

    full_path = os.path.join(PROJECT_ROOT, file_path)
    if not os.path.exists(full_path):
        print(f"  ✗ File not found: {full_path}")
        return False

    with open(full_path, "r", encoding="utf-8", errors="replace") as f:
        lines = f.readlines()

    # ── REPLACE ──────────────────────────────────────────────────
    # Strategy: prefer SUBSTRING replacement when the AI's `original_line`
    # is shorter than the actual file line (e.g. fixing `<riv>` inside
    # `<riv className="x">🧠</riv>`). The earlier whole-line replace lost
    # everything else on the line and corrupted JSX with two typos per line.
    def _do_replace_on_line(line, orig, fix):
        """Return the fixed version of `line`, preserving its line ending."""
        ending = "\n" if line.endswith("\n") else ""
        bare = line.rstrip("\n").rstrip("\r")
        orig_s = orig.strip()
        fix_s = fix.strip()

        if not orig_s or orig_s not in bare:
            return None  # no match

        # Case A: original IS the whole line (just maybe surrounded by
        # whitespace) — do a full-line replace and preserve indentation.
        if bare.strip() == orig_s:
            indent = bare[: len(bare) - len(bare.lstrip())]
            return indent + fix_s + ending

        # Case B: original is a substring → replace ONLY that substring,
        # keep everything else on the line intact. This is the case that
        # was broken before: lines with two typos (e.g. <riv>x</riv>)
        # had their tail (the emoji + closing tag) discarded by the old
        # whole-line replace.
        new_bare = bare.replace(orig_s, fix_s, 1)
        return new_bare + ending

    if action == "replace":
        # Strategy 1: use line number hint
        if line_number and 1 <= line_number <= len(lines):
            new_line = _do_replace_on_line(lines[line_number - 1], original, fixed)
            if new_line is not None:
                lines[line_number - 1] = new_line
                _write(full_path, lines)
                print_fix_diff(issue, line_number)
                return line_number

        # Strategy 2: search whole file
        for i, line in enumerate(lines):
            new_line = _do_replace_on_line(line, original, fixed)
            if new_line is not None:
                lines[i] = new_line
                _write(full_path, lines)
                print_fix_diff(issue, i + 1)
                return i + 1

        print(f"  ✗ [replace] could not find: {repr(original)} in {file_path}")
        return False

    # ── INSERT_BEFORE / INSERT_AFTER ─────────────────────────────
    if action in ("insert_before", "insert_after"):
        anchor = original.strip()
        target_idx = None

        # prefer line number hint first
        if line_number and 1 <= line_number <= len(lines):
            actual = lines[line_number - 1].rstrip("\n\r")
            if anchor in actual or actual.strip() in anchor:
                target_idx = line_number - 1

        # fallback: search whole file
        if target_idx is None:
            for i, line in enumerate(lines):
                if anchor in line:
                    target_idx = i
                    break

        if target_idx is None:
            print(f"  ✗ [{action}] anchor not found: {repr(original)} in {file_path}")
            return False

        # detect indentation from anchor line for consistency
        anchor_line = lines[target_idx]
        indent = len(anchor_line) - len(anchor_line.lstrip())
        new_line = " " * indent + fixed.strip() + "\n"

        insert_idx = target_idx if action == "insert_before" else target_idx + 1
        lines.insert(insert_idx, new_line)
        _write(full_path, lines)
        print_fix_diff(issue, target_idx + 1)
        return target_idx + 1

    return False


def _write(path, lines):
    with open(path, "w", encoding="utf-8") as f:
        f.writelines(lines)


# ── Pretty-print a single fix diff ───────────────────────────────


def print_fix_diff(issue, line_found):
    """Print a Jenkins-friendly before/after box for one fix."""
    file_path = issue.get("file_path", "?")
    action = issue.get("action", "replace")
    description = issue.get("description", "")
    original = issue.get("original_line", "").strip()
    fixed = issue.get("fixed_line", "").strip()
    lang = issue.get("language", "").upper()

    W = 70  # box width
    sep = "─" * W

    action_label = {
        "replace": "REPLACE  (broken line → fixed line)",
        "insert_before": "INSERT BEFORE anchor line",
        "insert_after": "INSERT AFTER  anchor line",
    }.get(action, action.upper())

    print(f"\n┌{sep}┐")
    print(f"│  🔧 AI FIX APPLIED  [{lang}]" + " " * (W - 22 - len(lang)) + "│")
    print(f"├{sep}┤")
    print(f"│  File   : {file_path[:W-12]:<{W-12}}│")
    print(f"│  Line   : {str(line_found):<{W-12}}│")
    print(f"│  Action : {action_label:<{W-12}}│")
    desc_short = description[: W - 12] if description else "-"
    print(f"│  Issue  : {desc_short:<{W-12}}│")
    print(f"├{sep}┤")

    if action == "replace":
        before_label = "  ✗ ERROR  "
        after_label = "  ✓ FIXED  "
    else:
        before_label = "  ⚓ ANCHOR "
        after_label = "  ✚ ADDED  "

    # Truncate long lines so they fit in the box
    max_code = W - 14
    orig_display = original[:max_code] + ("…" if len(original) > max_code else "")
    fixed_display = fixed[:max_code] + ("…" if len(fixed) > max_code else "")

    print(f"│{before_label}: {orig_display:<{max_code+2}}│")
    print(f"│           {'↓':<{W-11}}│")
    print(f"│{after_label}: {fixed_display:<{max_code+2}}│")
    print(f"└{sep}┘")


# ── Print full summary table of all applied fixes ─────────────────


def print_fix_summary(applied_fixes):
    """Print a compact table of all fixes applied this run."""
    if not applied_fixes:
        return

    print("\n")
    W = 72
    print("═" * W)
    title = f"  AI AUTO-FIX SUMMARY — {len(applied_fixes)} CHANGE(S) APPLIED  "
    print(title.center(W))
    print("═" * W)

    for idx, fix in enumerate(applied_fixes, 1):
        file_path = fix.get("file_path", "?")
        line_found = fix.get("line_found", "?")
        action = fix.get("action", "replace")
        original = fix.get("original_line", "").strip()
        fixed_line = fix.get("fixed_line", "").strip()
        description = fix.get("description", "")

        print(f"\n  #{idx}  {file_path}  (line {line_found})  [{action}]")
        print(f"       Issue : {description[:60]}")
        max_w = 60
        orig_d = original[:max_w] + ("…" if len(original) > max_w else "")
        fixed_d = fixed_line[:max_w] + ("…" if len(fixed_line) > max_w else "")

        if action == "replace":
            print(f"       BEFORE: {orig_d}")
            print(f"       AFTER : {fixed_d}")
        else:
            verb = "BEFORE" if action == "insert_before" else "AFTER"
            print(f"       ANCHOR ({verb}): {orig_d}")
            print(f"       INSERTED      : {fixed_d}")

        print(f"       {'─'*65}")

    print("═" * W)
    print()


# ── Run pytest ────────────────────────────────────────────────────


def run_tests():
    """
    Run pytest across every test directory found in the project.
    Discovers tests in: tests/, services/*/tests/, app/tests/, etc.
    Returns True if all found tests pass (or no tests exist).
    """
    import glob as _glob

    print("\nAI Analyzer: Running pytest to verify fixes...")

    # Find all test directories under the project root
    patterns = [
        os.path.join(PROJECT_ROOT, "tests"),
        os.path.join(PROJECT_ROOT, "services", "*", "tests"),
        os.path.join(PROJECT_ROOT, "app", "tests"),
    ]
    test_dirs = []
    for pat in patterns:
        for d in _glob.glob(pat):
            if os.path.isdir(d):
                test_dirs.append(d)

    if not test_dirs:
        print("  No test directories found — skipping test verification")
        return True  # nothing to fail; don't block the push

    print(
        f"  Found {len(test_dirs)} test dir(s): {[os.path.relpath(d, PROJECT_ROOT) for d in test_dirs]}"
    )

    all_passed = True
    for test_dir in test_dirs:
        svc_name = os.path.relpath(test_dir, PROJECT_ROOT)
        # Run pytest from the service root (parent of tests/) so that
        # `from app.app import ...` resolves correctly
        cwd = os.path.dirname(test_dir)
        result = subprocess.run(
            [sys.executable, "-m", "pytest", test_dir, "--tb=short", "-q"],
            capture_output=True,
            text=True,
            cwd=cwd,
        )
        if result.returncode == 0:
            print(f"  ✓ {svc_name}: all tests passed")
        elif result.returncode == 5:
            # Exit code 5 = no tests collected — treat as pass
            print(f"  ✓ {svc_name}: no tests collected (skipping)")
        else:
            print(f"  ✗ {svc_name}: test failures:")
            # Show only the failure summary lines, not the full traceback
            for line in (result.stdout + result.stderr).splitlines():
                if line.strip():
                    print(f"    {line}")
            all_passed = False

    if all_passed:
        print("AI Analyzer: All tests passed ✓")
    return all_passed


# ── Git commit and push ───────────────────────────────────────────


def git_commit_and_push(fixed_files, summary):
    import re as _re
    import base64 as _b64

    # ── Auto-push opt-in gate ───────────────────────────────────────
    # The AI analyzer can hallucinate "fixes" (e.g. corrupting a lockfile,
    # downgrading API model names to non-existent versions). Auto-pushing
    # those to GitHub turned a single bad batch into a broken main branch.
    # Default behaviour is now: report fixes, write them to disk locally,
    # but DO NOT commit or push unless AI_AUTO_PUSH=true is set.
    if os.environ.get("AI_AUTO_PUSH", "").lower() not in ("1", "true", "yes"):
        print("  ⏸  AI_AUTO_PUSH not enabled — skipping git commit/push.")
        print("     Fixes were applied to the workspace but NOT pushed to GitHub.")
        print("     Review the changes; if correct, set AI_AUTO_PUSH=true and re-run.")
        return False

    # ── Sanitize token (strip all non-alphanumeric-safe chars) ───────
    raw_token = os.environ.get("GITHUB_TOKEN", "")
    github_token = _re.sub(r"[^A-Za-z0-9_\-]", "", raw_token)
    if not github_token:
        print("  ⚠ GITHUB_TOKEN not set — push will fail")
        return False
    print(f"  Token length: {len(github_token)} chars")

    # ── Get remote URL and ensure it is plain HTTPS (no embedded token) ─
    repo_url = subprocess.run(
        ["git", "config", "--get", "remote.origin.url"],
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
    ).stdout.strip()

    # Convert SSH → HTTPS if needed; strip any embedded token
    if repo_url.startswith("git@github.com:"):
        repo_url = "https://github.com/" + repo_url[len("git@github.com:") :]
    clean_url = _re.sub(r"https://[^@]+@github\.com/", "https://github.com/", repo_url)
    subprocess.run(["git", "remote", "set-url", "origin", clean_url], cwd=PROJECT_ROOT)
    print(f"  Remote URL: {clean_url}")

    # ── Authenticate via HTTP Authorization header ────────────────────
    # This is the same method GitHub Actions uses. It avoids embedding
    # the token in the URL, which causes libcurl "Bad hostname" errors
    # on some macOS git installations when the URL is parsed.
    #
    # Header value = "Basic base64(x-access-token:<TOKEN>)"
    b64 = _b64.b64encode(f"x-access-token:{github_token}".encode()).decode()
    auth_header = f"Authorization: Basic {b64}"

    # Scope the header to github.com only and clear any credential helpers
    subprocess.run(
        ["git", "config", "http.https://github.com/.extraHeader", auth_header],
        cwd=PROJECT_ROOT,
    )
    subprocess.run(["git", "config", "credential.helper", ""], cwd=PROJECT_ROOT)
    # Disable interactive password prompts
    push_env = os.environ.copy()
    push_env["GIT_TERMINAL_PROMPT"] = "0"
    print("  ✓ HTTP Authorization header configured")
    print(f"  Token preview: {github_token[:4]}{'*' * (len(github_token) - 4)}")

    # ── Pre-push auth test — verify token BEFORE making a commit ─────
    # If this fails you'll see the real error (403, network, etc.) without
    # leaving behind an un-pushable local commit.
    print("  Testing auth with git ls-remote ...")
    ls = subprocess.run(
        ["git", "ls-remote", "--heads", "origin"],
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
        env=push_env,
    )
    if ls.returncode != 0:
        err = (ls.stderr + ls.stdout).strip()
        print(f"  ✗ Auth test FAILED — {err}")
        if "403" in err:
            print("  → Token lacks 'Contents: Write' permission on this repo.")
            print("    Fix: GitHub → Settings → Developer settings → Personal access tokens")
            print("    Classic PAT: enable 'repo' scope")
            print("    Fine-grained PAT: enable 'Contents: Read and Write'")
        elif "401" in err or "authentication" in err.lower():
            print("  → Token is invalid or expired — regenerate it in GitHub")
        elif "Could not resolve" in err or "Network" in err:
            print("  → Cannot reach github.com from Jenkins — check network/proxy")
        else:
            print("  → Unknown error — see above for details")
        # Cleanup before returning
        subprocess.run(
            ["git", "config", "--unset", "http.https://github.com/.extraHeader"],
            cwd=PROJECT_ROOT,
        )
        return False
    print("  ✓ Auth test passed — token is valid and can reach GitHub")

    # ── Git identity (required for commit) ────────────────────────────
    subprocess.run(
        ["git", "config", "user.email", "ai-bot@pipeline.local"], cwd=PROJECT_ROOT
    )
    subprocess.run(
        ["git", "config", "user.name", "AI-Remediation-Bot"], cwd=PROJECT_ROOT
    )

    # ── Stage fixed files ─────────────────────────────────────────────
    for fp in fixed_files:
        r = subprocess.run(
            ["git", "add", os.path.join(PROJECT_ROOT, fp)],
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT,
        )
        if r.returncode != 0:
            print(f"  ⚠ git add failed for {fp}: {r.stderr.strip()}")

    # ── Commit ────────────────────────────────────────────────────────
    msg = f"AI-Fix: {summary[:72]}"
    result = subprocess.run(
        ["git", "commit", "-m", msg], capture_output=True, text=True, cwd=PROJECT_ROOT
    )
    if result.returncode != 0:
        stderr = result.stderr.strip()
        if "nothing to commit" in stderr or "nothing added" in stderr:
            print("  AI Analyzer: nothing to commit (files unchanged on disk)")
            return False
        print(f"  AI Analyzer: git commit failed — {stderr}")
        return False
    print(f"  ✓ Committed: {msg}")

    # ── Push ──────────────────────────────────────────────────────────
    # GIT_CURL_VERBOSE=1 prints the full HTTP conversation on failure,
    # making it easy to see proxy errors, 403 responses, etc.
    verbose_env = push_env.copy()
    verbose_env["GIT_CURL_VERBOSE"] = "1"

    push = subprocess.run(
        ["git", "push", "origin", "HEAD:main"],
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
        env=verbose_env,
    )

    # Always clean up the auth header from git config after push attempt
    subprocess.run(
        ["git", "config", "--unset", "http.https://github.com/.extraHeader"],
        cwd=PROJECT_ROOT,
    )

    if push.returncode == 0:
        print("AI Analyzer:  Pushed fix to GitHub ✓")
        return True

    # Print FULL output so Jenkins console shows the exact HTTP response
    err = (push.stderr + "\n" + push.stdout).strip()
    print(f"AI Analyzer: ✗ Push FAILED (exit {push.returncode})")
    print("──── git push output ────")
    print(err)
    print("─────────────────────────")
    if "403" in err:
        print("  → CAUSE: 403 Forbidden")
        print("    Most common reasons:")
        print("    1. GITHUB_TOKEN missing/wrong in Jenkins Credentials store")
        print("    2. Token lacks write permission — needs 'repo' scope (classic PAT)")
        print("       or 'Contents: Read and Write' (fine-grained PAT)")
        print("    3. Branch protection rule blocks direct push to main")
        print("       Fix: GitHub repo → Settings → Branches → disable 'Require PR'")
    elif "401" in err or "authentication failed" in err.lower():
        print("  → CAUSE: 401 Unauthorized — token invalid or expired")
        print("    Fix: regenerate token at github.com → Settings → Developer settings")
    elif "rejected" in err and "non-fast-forward" in err:
        print("  → CAUSE: Remote main has commits the local branch does not")
        print("    Fix: the next build will pick up the latest and push cleanly")
    elif "Could not resolve" in err or "Network" in err or "proxy" in err.lower():
        print("  → CAUSE: Network/proxy blocking GitHub access from Jenkins machine")
        print("    Fix: run this on the Jenkins machine:")
        print("      git config --global http.proxy http://PROXY_HOST:PORT")
        print("      git config --global https.proxy http://PROXY_HOST:PORT")
    return False


# ── Main ──────────────────────────────────────────────────────────


def _auto_fix_html_structure(full_path, rel_path, errors):
    """
    Directly repair well-known HTML structural issues without needing AI.
    Returns True if the file was modified.
    """
    import re as _re

    try:
        with open(full_path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
        original = content
        lower = content.lower()

        # Collect which tags are missing
        missing = {err for err in errors}

        # ── Prepend <!DOCTYPE html> and <html lang="en"> if missing ──
        need_doctype = any("DOCTYPE" in e for e in missing)
        need_html = any("<html" in e.lower() for e in missing)

        if need_doctype or need_html:
            prefix = ""
            if need_doctype:
                prefix += "<!DOCTYPE html>\n"
            if need_html:
                prefix += '<html lang="en">\n'
            # Only prepend if the file doesn't start with these already
            stripped = content.lstrip()
            if not stripped.lower().startswith(
                "<!doctype"
            ) and not stripped.lower().startswith("<html"):
                # Remove any leading blank lines, then prepend
                content = prefix + stripped
                print(f"  ✓ Auto-fixed: added {prefix.strip()} to {rel_path}")

        # ── Append </body> and/or </html> if missing ──
        need_close_body = any("</body>" in e for e in missing)
        need_close_html = any("</html>" in e for e in missing)

        if need_close_body or need_close_html:
            tail = content.rstrip()
            if need_close_body and "</body>" not in content.lower():
                tail += "\n</body>"
                print(f"  ✓ Auto-fixed: appended </body> to {rel_path}")
            if need_close_html and "</html>" not in content.lower():
                tail += "\n</html>"
                print(f"  ✓ Auto-fixed: appended </html> to {rel_path}")
            content = tail + "\n"

        if content != original:
            with open(full_path, "w", encoding="utf-8") as f:
                f.write(content)
            return True
        return False

    except Exception as e:
        print(f"  ⚠ Could not auto-fix {rel_path}: {e}")
        return False


def _detect_and_fix_tag_typos(full_path, rel_path):
    """
    Deterministic JSX/HTML tag-typo detector.

    Scans the file for opening (<name ...>) and closing (</name>) tags whose
    `name` is NOT a valid HTML5 element AND is NOT a React component
    (capitalised, e.g. <DiagramCard>). Picks the closest valid HTML5 tag by
    edit distance and rewrites the file in place.

    This runs BEFORE the AI analysis so deterministic typos like
    <butto>, <dvi>, <riv>, <spam>, <buton> are fixed even if the AI is
    rate-limited or misses them.

    Returns a list of fix dicts: [{file, line, before, after}].
    """
    import re as _re
    from difflib import get_close_matches

    try:
        with open(full_path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
    except OSError:
        return []

    # Find every tag — opening or closing — whose name is all-lowercase.
    # We skip:
    #   - React components: capitalised first letter (<DiagramCard ...>)
    #   - Tags in JSX expressions / strings — accept some false positives;
    #     the post-fix validator catches anything that breaks compile.
    # Pattern: < or </ , followed by [a-z][a-z0-9]*
    tag_re = _re.compile(r"</?([a-z][a-z0-9]*)\b")

    fixes = []
    seen = set()  # don't re-suggest the same typo on every line

    for match in tag_re.finditer(content):
        name = match.group(1)
        if name in _VALID_HTML_TAGS:
            continue
        if name in seen:
            continue
        seen.add(name)

        # Find a plausible HTML5 element this might be a typo of.
        # cutoff 0.6 catches 3-char truncations like `but → button` (ratio
        # 0.667). At 0.7 we missed those and the file ended up with mixed
        # <button>...</but> pairs.
        candidates = get_close_matches(name, _VALID_HTML_TAGS, n=3, cutoff=0.6)
        if not candidates:
            continue
        suggested = candidates[0]

        # Bias: if any of the candidate valid tags is ALREADY used as an
        # opening tag in this file, prefer that one (handles closing-tag
        # typos like </but> when <button> opens elsewhere in the file).
        for c in candidates:
            opens = len(_re.findall(r"<" + _re.escape(c) + r"\b", content))
            if opens > 0:
                suggested = c
                break

        fixes.append({"name": name, "suggested": suggested})

    if not fixes:
        return []

    # Apply every fix: replace `<typo` with `<suggested` and `</typo>` with `</suggested>`.
    new_content = content
    applied = []
    for fix in fixes:
        typo = fix["name"]
        good = fix["suggested"]
        # Match boundary so `<butto` matches but `<button` doesn't
        open_re = _re.compile(r"<" + _re.escape(typo) + r"\b")
        close_re = _re.compile(r"</" + _re.escape(typo) + r"\b")
        before_count_open = len(open_re.findall(new_content))
        before_count_close = len(close_re.findall(new_content))
        new_content = open_re.sub(f"<{good}", new_content)
        new_content = close_re.sub(f"</{good}", new_content)
        if before_count_open or before_count_close:
            applied.append({
                "file": rel_path,
                "before": typo,
                "after": good,
                "open_count": before_count_open,
                "close_count": before_count_close,
            })

    if new_content != content:
        try:
            with open(full_path, "w", encoding="utf-8") as f:
                f.write(new_content)
        except OSError as e:
            print(f"  ⚠ Could not write tag-typo fix to {rel_path}: {e}")
            return []

    for f in applied:
        print(f"  🔧 Tag typo fixed in {f['file']}: "
              f"<{f['before']}>×{f['open_count']} </{f['before']}>×{f['close_count']} → "
              f"<{f['after']}>")
    return applied


def local_syntax_check():
    """
    Run fast local syntax checkers BEFORE calling the AI.
    Detects AND auto-fixes well-known structural errors (HTML skeleton tags,
    CSS brace imbalance context, JSX/HTML tag typos) so simple errors are
    resolved even when AI models are unavailable or hallucinating.

    Returns: (findings, auto_fixed_files)
      findings        — list of dicts [{file, tool, error}] for all issues found
      auto_fixed_files — set of rel_paths that were directly repaired
    """
    import re as _re

    findings = []
    auto_fixed_files = set()
    print("\nPre-flight: Local syntax checks...")

    # ── Pass 0: tag-typo auto-fix on JSX/HTML files ────────────────
    # Catches <butto>, <dvi>, <riv>, <spam>, <buton>, etc. via
    # difflib.get_close_matches against the HTML5 tag set. Runs first so
    # subsequent passes (and the AI) see clean tag names.
    for dirpath, dirnames, filenames in os.walk(PROJECT_ROOT):
        dirnames[:] = [
            d for d in dirnames if d not in SKIP_DIRS and not d.startswith(".")
        ]
        for filename in filenames:
            if filename in SKIP_FILES:
                continue
            if any(filename.endswith(p) for p in SKIP_FILE_PATTERNS):
                continue
            ext = os.path.splitext(filename)[1].lower()
            if ext not in (".jsx", ".tsx", ".html", ".htm"):
                continue
            full_path = os.path.join(dirpath, filename)
            rel_path = os.path.relpath(full_path, PROJECT_ROOT)
            tag_fixes = _detect_and_fix_tag_typos(full_path, rel_path)
            if tag_fixes:
                auto_fixed_files.add(rel_path)
                for tf in tag_fixes:
                    findings.append({
                        "file": rel_path,
                        "tool": "tag-typo-fixer",
                        "error": f"<{tf['before']}> → <{tf['after']}>",
                    })

    for dirpath, dirnames, filenames in os.walk(PROJECT_ROOT):
        dirnames[:] = [
            d for d in dirnames if d not in SKIP_DIRS and not d.startswith(".")
        ]
        for filename in filenames:
            ext = os.path.splitext(filename)[1].lower()
            full_path = os.path.join(dirpath, filename)
            rel_path = os.path.relpath(full_path, PROJECT_ROOT)

            # ── Python: use py_compile ──────────────────────────
            if ext == ".py":
                r = subprocess.run(
                    [sys.executable, "-m", "py_compile", full_path],
                    capture_output=True,
                    text=True,
                )
                if r.returncode != 0:
                    findings.append(
                        {
                            "file": rel_path,
                            "tool": "py_compile",
                            "error": r.stderr.strip(),
                        }
                    )
                    print(f"  ✗ Python syntax error: {rel_path}")
                    print(f"    {r.stderr.strip()}")

            # ── JavaScript: use node --check ────────────────────
            elif ext in (".js",):
                r = subprocess.run(
                    ["node", "--check", full_path], capture_output=True, text=True
                )
                if r.returncode != 0:
                    findings.append(
                        {"file": rel_path, "tool": "node", "error": r.stderr.strip()}
                    )
                    print(f"  ✗ JS syntax error: {rel_path}")
                    print(f"    {r.stderr.strip()}")

            # ── HTML: check CSS brace balance + extract/check JS ─
            elif ext in (".html", ".htm"):
                try:
                    with open(full_path, "r", encoding="utf-8", errors="replace") as f:
                        html_content = f.read()

                    # CSS brace balance check
                    css_blocks = _re.findall(
                        r"<style[^>]*>(.*?)</style>", html_content, _re.DOTALL
                    )
                    css_text = "".join(css_blocks)
                    opens = css_text.count("{")
                    closes = css_text.count("}")
                    if opens != closes:
                        msg = (
                            f"CSS brace mismatch: {opens} open vs {closes} close"
                            f" (delta: {opens - closes:+d})"
                        )
                        findings.append(
                            {"file": rel_path, "tool": "css-brace", "error": msg}
                        )
                        print(f"  ✗ {rel_path}: {msg}")

                        # Pin down the line
                        lines = html_content.splitlines()
                        depth = 0
                        in_style = False
                        for ln_num, ln in enumerate(lines, 1):
                            if "<style" in ln:
                                in_style = True
                            if "</style>" in ln:
                                in_style = False
                            if in_style:
                                for ch in ln:
                                    if ch == "{":
                                        depth += 1
                                    elif ch == "}":
                                        depth -= 1
                                if depth < 0:
                                    print(
                                        f"    First negative depth at line {ln_num}: {ln.strip()}"
                                    )
                                    break

                    # HTML structural checks — required skeleton tags
                    html_lower = html_content.lower()
                    struct_checks = [
                        ("<!doctype html>", "Missing <!DOCTYPE html> declaration"),
                        ("<html", "Missing <html> opening tag"),
                        ("</html>", "Missing </html> closing tag"),
                        ("<head", "Missing <head> opening tag"),
                        ("</head>", "Missing </head> closing tag"),
                        ("<body", "Missing <body> opening tag"),
                        ("</body>", "Missing </body> closing tag"),
                    ]
                    struct_errors = []
                    for needle, msg in struct_checks:
                        if needle not in html_lower:
                            findings.append(
                                {
                                    "file": rel_path,
                                    "tool": "html-structure",
                                    "error": msg,
                                }
                            )
                            struct_errors.append(msg)
                            print(f"  ✗ {rel_path}: {msg}")

                    # Auto-fix structural errors directly — no AI needed
                    if struct_errors:
                        if _auto_fix_html_structure(full_path, rel_path, struct_errors):
                            auto_fixed_files.add(rel_path)

                    # ── Invalid tag bulk-replace ──────────────────────
                    # Detect every non-standard HTML tag in the file.
                    # For each invalid tag we can confidently map to a
                    # real tag (e.g. <jt> → <div>), replace ALL occurrences
                    # in one pass — never call the AI for this, it will only
                    # fix a few lines at a time and leave the rest broken.
                    all_tags = set(_re.findall(r"</?([A-Za-z][A-Za-z0-9-]*)", html_content))
                    invalid_tags = {t for t in all_tags if t.lower() not in _VALID_HTML_TAGS}

                    if invalid_tags:
                        # Build a substitution map: guess the correct tag.
                        # Rules (in priority order):
                        #   1. If ALL the invalid tag's CSS classes match .div rules → div
                        #   2. If it wraps only inline content / is self-contained → span
                        #   3. Default → div  (block-level is almost always the intent)
                        sub_map = {}
                        for bad_tag in invalid_tags:
                            # Collect all class names this tag is ever given
                            classes_used = set(
                                c
                                for m in _re.finditer(
                                    rf'<{_re.escape(bad_tag)}[^>]*class="([^"]*)"',
                                    html_content, _re.IGNORECASE,
                                )
                                for c in m.group(1).split()
                            )
                            # Check which of those classes are styled as inline
                            inline_css_hint = False
                            for css_block in css_blocks:
                                for cls in classes_used:
                                    if _re.search(
                                        rf'\.{_re.escape(cls)}\s*\{{[^}}]*display\s*:\s*inline',
                                        css_block,
                                    ):
                                        inline_css_hint = True
                            sub_map[bad_tag.lower()] = "span" if inline_css_hint else "div"

                        # Apply all substitutions in one pass and report
                        fixed_content = html_content
                        total_replaced = 0
                        for bad_tag, good_tag in sub_map.items():
                            # opening tags:  <jt  →  <div   (preserve attributes)
                            new_content, n1 = _re.subn(
                                rf"(?i)<{_re.escape(bad_tag)}(\s|>|/>)",
                                lambda m, g=good_tag: f"<{g}{m.group(1)}",
                                fixed_content,
                            )
                            # closing tags:  </jt>  →  </div>
                            new_content, n2 = _re.subn(
                                rf"(?i)</{_re.escape(bad_tag)}>",
                                f"</{good_tag}>",
                                new_content,
                            )
                            fixed_content = new_content
                            total_replaced += n1 + n2
                            if n1 + n2:
                                msg = (
                                    f"Invalid HTML tag <{bad_tag}> used throughout file "
                                    f"({n1} opening + {n2} closing tags replaced with <{good_tag}>)"
                                )
                                findings.append({
                                    "file": rel_path,
                                    "tool": "html-invalid-tag",
                                    "error": msg,
                                })
                                print(f"  ✗ {rel_path}: {msg}")

                        if total_replaced > 0:
                            with open(full_path, "w", encoding="utf-8") as f:
                                f.write(fixed_content)

                            # Validate the result before marking as fixed
                            ok, reason = validate_html_fix(rel_path)
                            if ok:
                                # Update html_content so subsequent checks see fixed state
                                html_content = fixed_content
                                auto_fixed_files.add(rel_path)
                                print(
                                    f"  ✓ Auto-fixed {total_replaced} invalid tag(s) "
                                    f"in {rel_path} — no AI needed"
                                )
                            else:
                                # Revert to the ORIGINAL pre-fix content
                                with open(full_path, "w", encoding="utf-8") as f:
                                    f.write(html_content)  # html_content still holds original
                                print(
                                    f"  ⚠ Invalid-tag fix did not fully resolve {rel_path}: "
                                    f"{reason} — will pass to AI"
                                )

                    # Inline JS check
                    js_blocks = _re.findall(
                        r"<script[^>]*>(.*?)</script>", html_content, _re.DOTALL
                    )
                    if js_blocks:
                        js_tmp = "/tmp/_inline_js_check.js"
                        with open(js_tmp, "w") as jf:
                            jf.write("\n".join(js_blocks))
                        r = subprocess.run(
                            ["node", "--check", js_tmp], capture_output=True, text=True
                        )
                        if r.returncode != 0:
                            findings.append(
                                {
                                    "file": rel_path,
                                    "tool": "node-inline-js",
                                    "error": r.stderr.strip(),
                                }
                            )
                            print(f"  ✗ Inline JS error in {rel_path}")
                            print(f"    {r.stderr.strip()}")

                except Exception as e:
                    print(f"  Warning: could not check {rel_path} — {e}")

    if not findings:
        print("  ✓ All files passed local syntax checks")
    else:
        print(
            f"\n  Found {len(findings)} local syntax issue(s) — AI will also scan for fixes"
        )
    if auto_fixed_files:
        print(
            f"  ✓ Auto-fixed {len(auto_fixed_files)} file(s) locally: {sorted(auto_fixed_files)}"
        )
    return findings, auto_fixed_files


# ── HTML post-fix validator ───────────────────────────────────────
# Called after the AI applies fixes to an HTML file.
# If Gemini hallucinated invalid tag names (e.g. <jt>, <iv>) or broke
# the div balance / skeleton structure, we catch it here and REVERT.

# Complete set of valid HTML5 element names (covers 99 % of real usage).
_VALID_HTML_TAGS = {
    "a", "abbr", "address", "area", "article", "aside", "audio",
    "b", "base", "bdi", "bdo", "blockquote", "body", "br", "button",
    "canvas", "caption", "cite", "code", "col", "colgroup",
    "data", "datalist", "dd", "del", "details", "dfn", "dialog",
    "div", "dl", "dt",
    "em", "embed",
    "fieldset", "figcaption", "figure", "footer", "form",
    "h1", "h2", "h3", "h4", "h5", "h6",
    "head", "header", "hgroup", "hr", "html",
    "i", "iframe", "img", "input", "ins",
    "kbd", "label", "legend", "li", "link",
    "main", "map", "mark", "menu", "meta", "meter",
    "nav", "noscript",
    "object", "ol", "optgroup", "option", "output",
    "p", "picture", "pre", "progress",
    "q", "rp", "rt", "ruby",
    "s", "samp", "script", "section", "select", "small",
    "source", "span", "strong", "style", "sub", "summary", "sup",
    "table", "tbody", "td", "template", "textarea", "tfoot",
    "th", "thead", "time", "title", "tr", "track",
    "u", "ul", "var", "video", "wbr",
    # SVG elements that legitimately appear inside HTML
    "svg", "path", "circle", "rect", "line", "polygon",
    "polyline", "ellipse", "text", "tspan", "g", "defs",
    "use", "symbol", "clippath", "lineargradient",
    "radialgradient", "stop", "mask", "pattern", "filter",
    "feblend", "fecolormatrix", "fecomposite", "feconvolvematrix",
    "fediffuselighting", "fedisplacementmap", "feflood",
    "fegaussianblur", "feimage", "femerge", "femorphology",
    "feoffset", "fespecularlighting", "fetile", "feturbulence",
}


def validate_html_fix(rel_path):
    """
    Validate an HTML file after the AI has applied fixes.
    Returns (ok: bool, reason: str).

    Checks:
      1. No unknown / hallucinated tag names (e.g. <jt>, <iv>)
      2. <div> open/close count is balanced
      3. Required skeleton tags are present (DOCTYPE, html, head, body)
    """
    import re as _re

    full_path = os.path.join(PROJECT_ROOT, rel_path)
    try:
        with open(full_path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
    except OSError as e:
        return False, f"Cannot read file: {e}"

    # ── 1. Unknown tag check ──────────────────────────────────────
    # Extract every <tagname ...> and </tagname> — skip comments and DOCTYPE
    tag_names = _re.findall(r"</?([A-Za-z][A-Za-z0-9-]*)", content)
    unknown = {t for t in tag_names if t.lower() not in _VALID_HTML_TAGS}
    if unknown:
        return False, (
            f"AI introduced invalid/unknown HTML tag(s): {sorted(unknown)}. "
            "This is a hallucination — reverting the file."
        )

    # ── 2. <div> balance check ────────────────────────────────────
    div_opens  = len(_re.findall(r"<div[\s>]", content, _re.IGNORECASE))
    div_closes = content.lower().count("</div>")
    if div_opens != div_closes:
        return False, (
            f"<div> imbalance after fix: {div_opens} open vs {div_closes} close. "
            "Reverting."
        )

    # ── 3. Required skeleton tags ─────────────────────────────────
    lower = content.lower()
    for needle in ("<!doctype", "<html", "</html>", "<head", "</head>",
                   "<body", "</body>"):
        if needle not in lower:
            return False, f"Required tag '{needle}' missing after fix — reverting."

    return True, "OK"


def extract_json(text):
    """Strip markdown fences and extract the outermost {...} JSON object."""
    import re
    text = re.sub(r"```(?:json)?\s*", "", text)
    text = text.replace("```", "").strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(0))
        except json.JSONDecodeError:
            pass
    return None


def run_ai_batched(files_dict, providers):
    """
    Split files into size-bounded batches and call the AI providers once per
    batch. This replaces the old "send every file in one huge prompt" path
    which blew past Groq's per-request token budget and caused:
        400 — Please reduce the length of the messages or completion.

    providers is a list of (name, fn) tuples tried in order for each batch.
    Each fn(prompt) returns the raw response text, or None on failure.

    Returns a single merged analysis dict with all issues from all batches.
    """
    # 1. Pack files into batches no bigger than MAX_BATCH_CHARS
    batches = []
    current = {}
    current_chars = 0
    for label, meta in files_dict.items():
        size = len(meta["content"])
        # If a single chunk is already bigger than the batch limit, give it
        # its own batch (it still has to fit under the provider's hard limit,
        # but that's the chunker's job, not ours).
        if size >= MAX_BATCH_CHARS:
            if current:
                batches.append(current)
                current = {}
                current_chars = 0
            batches.append({label: meta})
            continue
        if current and current_chars + size > MAX_BATCH_CHARS:
            batches.append(current)
            current = {}
            current_chars = 0
        current[label] = meta
        current_chars += size
    if current:
        batches.append(current)

    print(f"  Packed {len(files_dict)} chunk(s) into {len(batches)} batch(es) "
          f"(max {MAX_BATCH_CHARS} chars each)")

    # 2. Call each provider per batch; collect all issues
    all_issues = []
    summaries = []
    any_batch_succeeded = False

    for i, batch in enumerate(batches, 1):
        # Wall-clock guard — bail out gracefully if we're out of time.
        if _RUN_START_TIME is not None:
            elapsed = time.time() - _RUN_START_TIME
            if elapsed > AI_ANALYSIS_BUDGET_SECS:
                print(f"\n  ⏱  Wall-clock budget exhausted "
                      f"({elapsed:.0f}s / {AI_ANALYSIS_BUDGET_SECS}s) — "
                      f"stopping after batch {i-1}/{len(batches)}")
                break

        batch_chars = sum(len(m["content"]) for m in batch.values())
        print(f"\n  ── Batch {i}/{len(batches)} "
              f"({len(batch)} file(s), {batch_chars} chars) ──")
        prompt = build_prompt(batch)

        raw = None
        for name, fn in providers:
            print(f"  Trying {name}...")
            raw = fn(prompt)
            if raw:
                break

        if not raw:
            print(f"  ⚠ Batch {i} — all providers failed; skipping this batch")
            continue

        analysis = extract_json(raw)
        if not analysis:
            print(f"  ⚠ Batch {i} — response wasn't valid JSON; skipping")
            continue

        any_batch_succeeded = True
        batch_issues = analysis.get("issues", []) or []
        all_issues.extend(batch_issues)
        if analysis.get("summary"):
            summaries.append(analysis["summary"])
        print(f"  ✓ Batch {i} — {len(batch_issues)} issue(s) found")

    if not any_batch_succeeded:
        return None

    return {
        "status": "issues_found" if all_issues else "clean",
        "summary": " | ".join(summaries) if summaries
                    else f"No issues found across {len(batches)} batch(es)",
        "issues": all_issues,
    }


def main():
    global _RUN_START_TIME
    _RUN_START_TIME = time.time()
    print("=" * 60)
    print("AI Code Analyzer — Powered by Groq → Gemini → Ollama")
    print(f"Project root: {PROJECT_ROOT}")
    print(f"Wall-clock budget: {AI_ANALYSIS_BUDGET_SECS}s "
          f"(override with AI_ANALYSIS_BUDGET_SECS env var)")
    print("=" * 60)

    # Step 0: fast local syntax checks — detects AND auto-fixes known issues
    local_findings, local_fixed_files = local_syntax_check()

    # Step 1: collect files
    print("\nStep 1: Collecting source files...")
    files = collect_files()
    seen_files = set()
    for label, meta in files.items():
        rp = meta["rel_path"]
        if rp not in seen_files:
            print(f"  → {rp} ({len(meta['content'])} chars in this chunk)")
            seen_files.add(rp)
    print(f"  Total: {len(seen_files)} file(s), {len(files)} chunk(s) sent to AI")

    # Step 2: build batched prompts and call the AI provider(s)
    # Provider order: Groq (JSON mode → no syntax errors) → Gemini → Ollama.
    # AI_PROVIDER env var can force a specific provider for testing.
    provider_override = os.environ.get("AI_PROVIDER", "").lower().strip()

    # Build the (name, fn) list in the order we'll try them PER BATCH.
    if provider_override == "groq":
        providers = [("Groq", call_groq_analyze)]
    elif provider_override == "gemini":
        providers = [("Gemini", call_gemini_analyze)]
    elif provider_override == "ollama":
        providers = [("Ollama", call_ollama_analyze)]
    else:
        providers = []
        if os.environ.get("GROQ_API_KEY"):
            providers.append(("Groq", call_groq_analyze))
        if os.environ.get("GEMINI_API_KEY"):
            providers.append(("Gemini", call_gemini_analyze))
        # Ollama is always available as a last-resort local fallback
        providers.append(("Ollama", call_ollama_analyze))

    print(f"\nStep 2: Sending files to AI in batches (providers: "
          f"{', '.join(n for n, _ in providers)})...")

    analysis = run_ai_batched(files, providers)

    if analysis is None:
        print("\nAI Analyzer: All providers (Groq, Gemini, Ollama) unavailable — skipping AI analysis.")
        if local_fixed_files:
            print(f"  Pushing {len(local_fixed_files)} local auto-fix(es) to GitHub...")
            summary = "auto-fix: HTML structural errors repaired by local checker"
            git_commit_and_push(list(local_fixed_files), summary)
        else:
            print("Lint and Test stages will catch any errors ✓")
        sys.exit(0)

    print(f"\nStep 3: Merged analysis across all batches:")
    print(f"  Status : {analysis.get('status')}")
    print(f"  Summary: {analysis.get('summary', '')}")
    print(f"  Issues : {len(analysis.get('issues', []))}\n")

    with open(ANALYSIS_LOG, "w") as f:
        f.write(json.dumps(analysis, indent=2))

    if analysis.get("status") == "clean" or not analysis.get("issues"):
        print("AI Analyzer: No syntax errors found by AI.")
        if local_fixed_files:
            print(f"  Pushing {len(local_fixed_files)} local auto-fix(es) to GitHub...")
            summary = "auto-fix: HTML structural errors repaired by local checker"
            git_commit_and_push(list(local_fixed_files), summary)
        else:
            print("  All files are clean ✓")
        sys.exit(0)

    # Step 4: report and filter issues
    # Build the set of real file paths that were actually sent to the AI.
    # Any issue whose file_path is NOT in this set is a hallucination
    # (Ollama in particular tends to invent plausible-looking but wrong paths).
    real_paths = set()
    for meta in files.values():
        real_paths.add(meta["rel_path"])
        # Also accept the label itself (e.g. "frontend/index.html [chunk 1]")
        # by stripping the chunk suffix
        real_paths.add(meta["rel_path"].split(" [")[0])

    raw_issues = analysis.get("issues", [])
    issues = []
    hallucinated = []
    for i in raw_issues:
        if i.get("severity") != "error":
            continue
        fp = i.get("file_path", "")
        if fp in real_paths:
            issues.append(i)
        else:
            hallucinated.append(fp)

    if hallucinated:
        unique_hallucinated = sorted(set(hallucinated))
        print(
            f"  ⚠ Ignoring {len(hallucinated)} issue(s) for non-existent paths "
            f"(AI hallucination): {unique_hallucinated}"
        )

    print(f"AI Analyzer: Found {len(issues)} valid error(s) in real project files")
    print(f"Summary: {analysis.get('summary', '')}\n")
    for issue in issues:
        action = issue.get("action", "replace")
        print(
            f"  [{issue.get('severity', '?').upper()}] {issue['file_path']} "
            f"line {issue.get('line_number', '?')} [{action}]: {issue['description']}"
        )

    # Step 5: apply fixes — process each file in reverse line order
    print("\nStep 4: Applying fixes...")
    # Seed fixed_files with anything the local checker already repaired,
    # so both local and AI fixes land in a single commit.
    fixed_files = set(local_fixed_files)
    applied = 0
    applied_fixes = []  # track details for summary

    by_file = defaultdict(list)
    for issue in issues:
        if is_safe_fix(issue):
            by_file[issue["file_path"]].append(issue)

    for file_path, file_issues in by_file.items():

        # ── Snapshot the file BEFORE any changes ─────────────────
        # If our post-fix validation fails we restore this backup,
        # so a bad AI fix can never be committed to GitHub.
        full_path = os.path.join(PROJECT_ROOT, file_path)
        try:
            with open(full_path, "r", encoding="utf-8", errors="replace") as _f:
                _original_content = _f.read()
        except OSError:
            _original_content = None

        # reverse order: insertions/replacements at higher line numbers first
        # so that earlier line numbers are not shifted
        file_applied = 0
        for issue in sorted(
            file_issues, key=lambda x: x.get("line_number", 0), reverse=True
        ):
            result = apply_fix(issue)
            if result is not False:
                file_applied += 1
                applied += 1
                # Record for the summary table
                applied_fixes.append({**issue, "line_found": result})

        if file_applied == 0:
            continue  # nothing changed for this file — skip validation

        # ── Post-fix validation gate ──────────────────────────────
        # For Python: re-compile to catch introduced syntax errors.
        # For HTML:   check tag names, div balance, skeleton tags.
        # If validation fails → REVERT to original and skip this file.
        revert_reason = None

        if file_path.endswith(".py"):
            r = subprocess.run(
                [sys.executable, "-m", "py_compile", full_path],
                capture_output=True, text=True,
            )
            if r.returncode != 0:
                revert_reason = f"py_compile failed: {r.stderr.strip()}"

        elif file_path.endswith((".html", ".htm")):
            ok, reason = validate_html_fix(file_path)
            if not ok:
                revert_reason = reason

        if revert_reason:
            print(f"\n  ✗ POST-FIX VALIDATION FAILED for {file_path}:")
            print(f"    Reason : {revert_reason}")
            if _original_content is not None:
                with open(full_path, "w", encoding="utf-8") as _f:
                    _f.write(_original_content)
                print(f"    Action : File REVERTED to original — will NOT be committed")
            else:
                print(f"    Action : Could not revert (no backup) — file may be broken")
            # Subtract the fixes we just "applied" — they're now undone
            applied -= file_applied
            applied_fixes = [x for x in applied_fixes
                             if x.get("file_path") != file_path]
        else:
            fixed_files.add(file_path)
            print(f"  ✓ Post-fix validation passed for {file_path}")

    # Print the full summary diff table after all fixes
    print_fix_summary(applied_fixes)
    print(f"Applied {applied} fix(es) across {len(fixed_files)} file(s)")

    if applied == 0:
        print("AI Analyzer: No valid AI fixes could be applied.")
        if local_fixed_files:
            print(f"  Pushing {len(local_fixed_files)} local auto-fix(es) to GitHub...")
            summary = "auto-fix: HTML structural errors repaired by local checker"
            git_commit_and_push(list(local_fixed_files), summary)
        else:
            print("Lint and Test stages will catch real errors ✓")
        sys.exit(0)

    # Step 6: verify Python files compile cleanly (second pass — catches
    # any files the per-file gate above may have missed, e.g. local fixes)
    print("\nStep 5: Verifying Python syntax on modified files...")
    syntax_ok = True
    for fp in fixed_files:
        if not fp.endswith(".py"):
            continue
        full_path = os.path.join(PROJECT_ROOT, fp)
        r = subprocess.run(
            [sys.executable, "-m", "py_compile", full_path],
            capture_output=True,
            text=True,
        )
        if r.returncode != 0:
            print(f"  ✗ {fp}: syntax error after fix — {r.stderr.strip()}")
            syntax_ok = False
        else:
            print(f"  ✓ {fp}: syntax OK")

    if not syntax_ok:
        print("\nAI Analyzer: A fix introduced a syntax error — NOT pushing.")
        sys.exit(2)

    # Step 7: run tests
    if not run_tests():
        print("\nAI Analyzer: Tests still failing — NOT pushing to GitHub.")
        sys.exit(2)

    # Step 8: commit and push
    summary = analysis.get("summary", "fixed syntax errors detected by Gemini")
    committed = git_commit_and_push(list(fixed_files), summary)

    if committed:
        print("\nAI Analyzer: Self-healing complete ✓")
        sys.exit(1)
    else:
        print("\nAI Analyzer: Push failed")
        sys.exit(2)


if __name__ == "__main__":
    main()
